// ============================================================================
// agentic-test — GitHub Actions Workflow Generator
// ============================================================================

import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';

/**
 * Generate a GitHub Actions workflow for running agent tests.
 */
export function generateGitHubActionsWorkflow(options: {
    nodeVersion?: string;
    secrets?: string[];
    schedule?: string;
    saveResults?: boolean;
} = {}): string {
    const nodeVersion = options.nodeVersion ?? '20';
    const secrets = options.secrets ?? [];
    const schedule = options.schedule ?? '';
    const saveResults = options.saveResults ?? true;

    let envBlock = '';
    if (secrets.length > 0) {
        envBlock = '\n        env:\n' +
            secrets.map((s) => `          ${s}: \${{ secrets.${s} }}`).join('\n');
    }

    const scheduleBlock = schedule
        ? `\n  schedule:\n    - cron: '${schedule}'`
        : '';

    return `# ============================================================================
# agentic-test — AI Agent Test Pipeline
# Generated by: agentic-test ci --setup
# ============================================================================

name: Agent Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]${scheduleBlock}

jobs:
  agent-tests:
    name: 🤖 Run Agent Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js ${nodeVersion}
        uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersion}'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run agent tests
        run: npx agentic-test run --reporter console --reporter junit --output ./test-results${envBlock}

      - name: 📊 Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: agent-test-results
          path: ./test-results/
          retention-days: 30
${saveResults ? `
      - name: 💾 Save results for dashboard
        if: github.ref == 'refs/heads/main'
        run: npx agentic-test run --save
` : ''}
      - name: 📝 Test Summary
        if: always()
        run: |
          echo "## 🤖 Agent Test Results" >> $GITHUB_STEP_SUMMARY
          if [ -f ./test-results/junit.xml ]; then
            echo "Results saved to artifacts" >> $GITHUB_STEP_SUMMARY
          fi
`;
}

/**
 * Write the workflow file to disk.
 */
export function scaffoldGitHubActions(
    projectDir: string = '.',
    options: Parameters<typeof generateGitHubActionsWorkflow>[0] = {},
): string {
    const workflowDir = resolve(projectDir, '.github', 'workflows');
    if (!existsSync(workflowDir)) {
        mkdirSync(workflowDir, { recursive: true });
    }

    const filepath = join(workflowDir, 'agent-tests.yml');
    const content = generateGitHubActionsWorkflow(options);
    writeFileSync(filepath, content, 'utf-8');
    return filepath;
}
